# -*- coding: utf-8 -*-
"""alerta_notas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DPw8ayBlevPV18tvYi7vyY9vdn3cgR1-
"""

import sqlite3

def criar_banco_de_dados():
    conexao = sqlite3.connect('Escola.db')
    cursor = conexao.cursor()
    cursor.execute('''
    CREATE TABLE IF NOT EXISTS alunos_notas (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        nome TEXT NOT NULL,
        email_responsavel TEXT NOT NULL,
        nota REAL NOT NULL
    )
    ''')
    conexao.commit()
    conexao.close()

def inserir_dados_exemplo():
    conexao = sqlite3.connect('Escola.db')
    cursor = conexao.cursor()
    # Usamos o comando IGNORE ou verificamos se já existem dados para não duplicar toda segunda-feira
    cursor.execute("SELECT COUNT(*) FROM alunos_notas")
    if cursor.fetchone()[0] == 0:
        dados_alunos = [
            ('João Silva', 'joao.responsavel@email.com', 8.5),
            ('Maria Souza', 'maria.responsavel@email.com', 6.8),
            ('Pedro Santos', 'pedro.responsavel@email.com', 9.1),
            ('Ana Oliveira', 'ana.responsavel@email.com', 5.5),
            ('Carlos Lima', 'carlos.responsavel@email.com', 7.0)
        ]
        cursor.executemany("INSERT INTO alunos_notas (nome, email_responsavel, nota) VALUES (?, ?, ?)", dados_alunos)
        conexao.commit()
    conexao.close()

def buscar_alunos_em_risco():
    conexao = sqlite3.connect('Escola.db')
    cursor = conexao.cursor()
    query = "SELECT nome, email_responsavel, nota FROM alunos_notas WHERE nota < 7.0"
    cursor.execute(query)
    alunos_em_risco = cursor.fetchall()
    conexao.close()
    return alunos_em_risco

# ESTA É A PARTE QUE O GITHUB ACTIONS VAI EXECUTAR
if __name__ == "__main__":
    criar_banco_de_dados()
    inserir_dados_exemplo()
    lista = buscar_alunos_em_risco()

    print('--- RELATÓRIO DE DESEMPENHO ESCOLAR ---')
    if lista:
        for aluno in lista:
            print(f'ALERTA: Aluno {aluno[0]} com nota {aluno[2]}. Notificar: {aluno[1]}')
    else:
        print('Nenhum aluno em risco identificado.')